spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  servlet:
    session:
      cookie:
        secure: ${COOKIE_SECURE:false}
        same-site: lax

